teams:
  - name: cello-admins
    maintainers:
      - ryjones
    members:
      - yeasy
#    members:
      - fengyangsy
      - xichen1
      - zhuyuanmao
  - name: cello-contributors
    maintainers:
      - ryjones
    members:
      - yeasy
#    members:
      - YoungHypo
      - fengyangsy
      - link1697
      - xiaor2
      - xichen1
      - zhuyuanmao
  - name: cello-maintainers
    maintainers:
      - ryjones
    members:
      - yeasy
#    members:
      - fengyangsy
      - xichen1
      - zhuyuanmao
  - name: staff
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
repositories:
  - name: governance
    teams:
      staff: maintain
    visibility: public
#  - name: cello
#    teams:
#      cello-admins: admin
#      cello-analytics-maintainers: write
#      cello-contributors: write
#      cello-maintainers: maintain
#    visibility: public
