teams:
  - name: cello-admins
    maintainers:
      - yeasy
    members:
      - fengyangsy
      - xichen1
      - zhuyuanmao
  - name: cello-contributors
    maintainers:
      - yeasy
    members:
      - YoungHypo
      - fengyangsy
      - link1697
      - xiaor2
      - xichen1
      - zhuyuanmao
  - name: cello-maintainers
    maintainers:
      - yeasy
    members:
      - fengyangsy
      - xichen1
      - zhuyuanmao
  - name: staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: governance
    teams:
      staff: maintain
    visibility: public
  - name: cello
    teams:
      cello-admins: admin
      cello-contributors: write
      cello-maintainers: maintain
    visibility: public
